ASP.Net/MinMVC/MVCSample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ModelTest.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ASP.Net/MinMVC/MVCSample/Controllers/ModelSampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations;

namespace ModelTest.Controllers
{
    public class ModelSampleController : Controller
    {
        //
        // GET: /MyModel/

        #region UIHintAttributeSample
        public ActionResult UIHintAttributeSample()
        {
            return View(new DemoModel());
        }
        public class ModelMetadataInfo
        {
            public ModelMetadata ModelMetadata { get; set; }
            public Expression<Func<ModelMetadata, object>>[] PropertyAccessors { get; private set; }
            public ModelMetadataInfo(Type modelType, params Expression<Func<ModelMetadata, object>>[] propertyAccessors)
            {
                this.ModelMetadata = new ModelMetadata(ModelMetadataProviders.Current, null, null, modelType, null);
                this.PropertyAccessors = propertyAccessors;
            }
        }
        public class DemoModel
        {
            public string Foo { get; set; }
            [UIHint("AAA")]
            public string Bar { get; set; }
            [Display(Prompt="Water",Name="ddd",ShortName="222")]
            public string Baz { get; set; }
            public bool A { get; set; }
        }
        #endregion


    }
}

ASP.Net/MinMVC/MVCSample/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @Html.ActionLink("UIHintAttributeSample", "UIHintAttributeSample", "ModelSample");
    </div>
</body>
</html>

ASP.Net/MinMVC/MVCSample/Views/ModelSample/UIHintAttributeSample.cshtml
@{
    Layout = null;
}
@model ModelTest.Controllers.ModelSampleController.DemoModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UIHintAttributeSample</title>
</head>
<body>
    <div>
        @using(Html.BeginForm(null,null,FormMethod.Get))
        {
        @Html.EditorFor(o => o.A);
        <input type="submit" />
        }
    </div>
</body>
</html>